name: Cypress Tests
on: [push]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  statuses: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Esto crea las 3 máquinas que vimos en tu captura de pantalla
        containers: [1, 2, 3] 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: yarn install
          record: true
          parallel: true
          # CONFIGURACIÓN DEL NOMBRE DEL GRUPO
          # Esto cambiará "Unnamed" por el nombre de la rama y el navegador
          group: 'UI Tests - ${{ github.ref_name }} - Chrome'
          # Opcional: añade etiquetas para filtrar mejor en el dashboard
          tag: '${{ github.event_name }}, chrome'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Cypress Report Summary
        if: always()
        run: |
          echo "### Cypress Results Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "Ejecución finalizada en el contenedor #${{ matrix.containers }}." >> $GITHUB_STEP_SUMMARY
          echo "Revisa los detalles completos en [Cypress Cloud](https://cloud.cypress.io)." >> $GITHUB_STEP_SUMMARY
